### ISSUE TITLE
i am using the same code for the regularization code but getting only 66% accuracy instead of 83%,Please help

### ISSUE THREAD

**Issue by Nikhil5555** [suraggupta/coursera-machine-learning-solutions-python#5]
Which part i am doing wrong?

**Comment by ashimdahal** [comment]
try using CG method for optimize.minimize

**Comment by suraggupta** [comment]
@Nikhil5555 Which part of the exercises/notebook are you referring to? Could you provide a reprex?

**Comment by Nikhil5555** [comment]
> try using CG method for optimize.minimize 

Got it, Thanks

**Comment by NoLandMen496** [comment]
Nikhil and suraggupta there is a simple but important error on the computation of the cost & grad with regularisation: temp = theta is wrong, it should be temp = theta.copy() because in the next line, temp[0] = 0, therefore you are making theta[0] = 0 also.

numpy arrays are passed by reference in python hence the need to make a new copy otherwise you are making both theta[0] and temp[0]  zero.

This is the reason why the cost and grad comes wrong with regularisation in ex2 and ex3. suraggupta used copy() in ex1 but forgot to use that in ex2 and ex3. Besides that suraggupta made an AWESOME job with this github.
